
spring.datasource.url=jdbc:postgresql://localhost:5432/fooddeliverydb10
spring.datasource.username=postgres
spring.datasource.password=gta vc vv 0928

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
